name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.0
        with:
          version: 6.15.1

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install deps
        run: pnpm install
        
      - name: Run Lint
        run: pnpm lint
        
      - name: Prettier Check
        run: pnpm prettier
        
      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm run build
